const prisma = require('../config/prisma');
const { validateEAN13, generateEAN13 } = require('../utils/barcode');

class SkuService {

  /**
   * Crear un nuevo SKU para un producto existente
   */
  async createSku(data) {
    const { productId, code, price, stock, attributes, barcode, barcodeType, isAutoGenerated } = data;
    
    // Validar producto
    const product = await prisma.product.findUnique({ where: { id: parseInt(productId) } });
    if (!product) throw new Error('Producto no encontrado');

    return await prisma.$transaction(async (tx) => {
        let finalBarcode = barcode;

        // 1. Auto-Generación
        if (barcodeType === 'EAN13' && isAutoGenerated) {
            // Obtener y actualizar secuencia
            const seqRecord = await tx.barcodeSequence.upsert({
                where: { id: 1 },
                update: { lastSequence: { increment: 1 } },
                create: { id: 1, prefix: '779999', lastSequence: 1 }
            });

            finalBarcode = generateEAN13(seqRecord.prefix, seqRecord.lastSequence);
        } 
        // 2. Validación Manual
        else if (barcodeType === 'EAN13' && finalBarcode) {
            if (!validateEAN13(finalBarcode)) {
                throw new Error('El código EAN-13 es inválido (Dígito verificador incorrecto o formato erróneo).');
            }
        }

        // 3. Unicidad (Prisma unique constraint lo atrapa, pero podemos pre-checkear si queremos msj custom)
        if (finalBarcode) {
            const existing = await tx.sKU.findUnique({ where: { barcode: finalBarcode } });
            if (existing) throw new Error(`El código de barras ${finalBarcode} ya está en uso.`);
        }

        const newSku = await tx.sKU.create({
            data: {
                productId: parseInt(productId),
                code,
                price: price != null && price !== '' ? price : product.basePrice,
                stock: stock || 0,
                barcode: finalBarcode,
                barcodeType: barcodeType || 'INTERNO',
                isAutoGenerated: !!isAutoGenerated
            }
        });

        if (attributes && Array.isArray(attributes)) {
            await tx.variantOption.createMany({
                data: attributes.map(attr => ({
                    skuId: newSku.id,
                    name: attr.name,
                    value: attr.value
                }))
            });
        }
        
        return newSku;
    });
  }

  /**
   * Actualizar datos de un SKU (Precio, status, borrar atributos viejos y poner nuevos)
   * NO actualiza stock (usar endpoint dedicado)
   */
  async updateSku(id, data) {
    const { price, active, attributes, stock, code, barcode, barcodeType } = data;
    
    return await prisma.$transaction(async (tx) => {
       // Validar existencia para las reglas de integridad
       const currentSku = await tx.sKU.findUnique({ where: { id: parseInt(id) } });
       if (!currentSku) throw new Error("SKU no encontrado");

       // Regla 5: No modificar código si tiene ventas (y está cambiando el código)
       if (barcode && currentSku.barcode && barcode !== currentSku.barcode) {
           if (currentSku.soldQuantity > 0) {
               throw new Error("No se puede modificar el código de barras de un producto con historial de ventas.");
           }
       }

       let finalBarcode = barcode === "" ? null : barcode;
       // Validar EAN si cambia
       if (barcodeType === 'EAN13' && finalBarcode && finalBarcode !== currentSku.barcode) {
            if (!validateEAN13(finalBarcode)) {
                throw new Error('El código EAN-13 es inválido.');
            }
       }

       // Actualizar
       const sku = await tx.sKU.update({
         where: { id: parseInt(id) },
         data: { 
             price, 
             active,
             ...(stock !== undefined && { stock }),
             ...(code && { code }),
             ...(barcode !== undefined && { barcode: finalBarcode }),
             ...(barcodeType && { barcodeType })
         }
       });

       // Si vienen atributos, reemplazamos (estrategia simple: borrar y crear)
       if (attributes && Array.isArray(attributes)) {
          await tx.variantOption.deleteMany({ where: { skuId: parseInt(id) } });
          
          await tx.variantOption.createMany({
              data: attributes.map(attr => ({
                  skuId: sku.id,
                  name: attr.name,
                  value: attr.value
              }))
          });
       }

       return tx.sKU.findUnique({
           where: { id: parseInt(id) },
           include: { variantOptions: true }
       });
    }, {
        maxWait: 20000, 
        timeout: 25000 
    });
  }

  /**
   * Eliminar un SKU
   * Regla: No borrar si tiene ventas history
   */
  async deleteSku(id) {
      const sku = await prisma.sKU.findUnique({ where: { id: parseInt(id) } });
      if (!sku) throw new Error('SKU no encontrado');

      if (sku.soldQuantity > 0) {
          throw new Error('No se puede eliminar un SKU con ventas registradas. Considere pausarlo (active: false).');
      }

      return await prisma.sKU.delete({ where: { id: parseInt(id) } });
  }

  /**
   * Actualizar stock de una variante
   */
  async updateStock(skuId, quantity, operationType = 'set') {
    // operationType: 'set' (fixed value), 'add' (increment), 'subtract' (decrement)
    
    const sku = await prisma.sKU.findUnique({ where: { id: parseInt(skuId) } });
    if (!sku) throw new Error('SKU no encontrado');

    let newStock = sku.stock;

    if (operationType === 'add') newStock += quantity;
    else if (operationType === 'subtract') newStock -= quantity;
    else newStock = quantity;

    if (newStock < 0) throw new Error('El stock no puede ser negativo');

    return await prisma.sKU.update({
      where: { id: parseInt(skuId) },
      data: { stock: newStock }
    });
  }

  async getSkusByProduct(productId) {
    return await prisma.sKU.findMany({
      where: { productId: parseInt(productId) },
      include: { variantOptions: true }
    });
  }

  async findAll(params = {}) {
      const { search, limit = 20 } = params;
      const where = { active: true };

      if (search) {
          where.OR = [
              { code: { contains: search, mode: 'insensitive' } },
              { product: { name: { contains: search, mode: 'insensitive' } } }
          ];
      }

      return await prisma.sKU.findMany({
          where,
          take: parseInt(limit),
          include: { 
              product: { select: { name: true, images: true, measurementUnit: true } },
              variantOptions: true 
          },
          orderBy: { code: 'asc' }
      });
  }
}

module.exports = new SkuService();
